version: "2"

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - govet
    - staticcheck
    - revive
    - errcheck
    - ineffassign
    - iface
    - dupl
    - funlen
    - nestif
    - maintidx

  settings:
    govet:
      enable-all: true

    iface:
      enable:
        - identical
        - unused
        - opaque
        - unexported

    dupl:
      threshold: 120

    funlen:
      lines: 120
      statements: 70
      ignore-comments: true

    nestif:
      min-complexity: 15

    maintidx:
      under: 25

  exclusions:
    rules:
      - path: _test\.go
        linters:
          - cyclop
          - gocognit
          - funlen
          - nestif
          - dupl
          - maintidx
      - path: _test\.go
        text: "unused-parameter:"
        linters:
          - revive
      - path: _test\.go
        linters:
          - govet
        text: "fieldalignment"
