package xsd

const (
	xmlVersion10 = "1.0"
	xmlPrefix    = "xml"
	xmlAttrBase  = "base"
	xmlAttrID    = "id"
	xmlAttrLang  = "lang"
	xmlAttrSpace = "space"
	xmlnsPrefix  = "xmlns"

	xmlValueDefault  = "default"
	xmlValuePreserve = "preserve"

	xlinkAttrActuate = "actuate"
	xlinkAttrArcrole = "arcrole"
	xlinkAttrHref    = "href"
	xlinkAttrRole    = "role"
	xlinkAttrShow    = "show"
	xlinkAttrTitle   = "title"
	xlinkAttrType    = "type"

	xsiAttrNil                       = "nil"
	xsiAttrNoNamespaceSchemaLocation = "noNamespaceSchemaLocation"
	xsiAttrSchemaLocation            = "schemaLocation"
	xsiAttrType                      = "type"

	xsdElemAll            = "all"
	xsdElemAnnotation     = "annotation"
	xsdElemAny            = "any"
	xsdElemAnyAttribute   = "anyAttribute"
	xsdElemAppinfo        = "appinfo"
	xsdElemAttribute      = "attribute"
	xsdElemAttributeGroup = "attributeGroup"
	xsdElemChoice         = "choice"
	xsdElemComplexContent = "complexContent"
	xsdElemComplexType    = "complexType"
	xsdElemDocumentation  = "documentation"
	xsdElemElement        = "element"
	xsdElemExtension      = "extension"
	xsdElemField          = "field"
	xsdElemGroup          = "group"
	xsdElemImport         = "import"
	xsdElemInclude        = "include"
	xsdElemKey            = "key"
	xsdElemKeyref         = "keyref"
	xsdElemList           = "list"
	xsdElemNotation       = "notation"
	xsdElemRestriction    = "restriction"
	xsdElemSchema         = "schema"
	xsdElemSelector       = "selector"
	xsdElemSequence       = "sequence"
	xsdElemSimpleContent  = "simpleContent"
	xsdElemSimpleType     = "simpleType"
	xsdElemUnion          = "union"
	xsdElemUnique         = "unique"

	xsdAttrAbstract             = "abstract"
	xsdAttrAttributeFormDefault = "attributeFormDefault"
	xsdAttrBase                 = "base"
	xsdAttrBlock                = "block"
	xsdAttrBlockDefault         = "blockDefault"
	xsdAttrDefault              = "default"
	xsdAttrElementFormDefault   = "elementFormDefault"
	xsdAttrFinal                = "final"
	xsdAttrFinalDefault         = "finalDefault"
	xsdAttrFixed                = "fixed"
	xsdAttrForm                 = "form"
	xsdAttrID                   = "id"
	xsdAttrItemType             = "itemType"
	xsdAttrMaxOccurs            = "maxOccurs"
	xsdAttrMemberTypes          = "memberTypes"
	xsdAttrMinOccurs            = "minOccurs"
	xsdAttrMixed                = "mixed"
	xsdAttrName                 = "name"
	xsdAttrNamespace            = "namespace"
	xsdAttrNillable             = "nillable"
	xsdAttrNotNamespace         = "notNamespace"
	xsdAttrNotQName             = "notQName"
	xsdAttrProcessContents      = "processContents"
	xsdAttrPublic               = "public"
	xsdAttrRef                  = "ref"
	xsdAttrRefer                = "refer"
	xsdAttrSchemaLocation       = "schemaLocation"
	xsdAttrSource               = "source"
	xsdAttrSubstitutionGroup    = "substitutionGroup"
	xsdAttrSystem               = "system"
	xsdAttrTargetNamespace      = "targetNamespace"
	xsdAttrType                 = "type"
	xsdAttrUse                  = "use"
	xsdAttrValue                = "value"
	xsdAttrVersion              = "version"
	xsdAttrXPath                = "xpath"

	xsdFacetEnumeration    = "enumeration"
	xsdFacetFractionDigits = "fractionDigits"
	xsdFacetLength         = "length"
	xsdFacetMaxExclusive   = "maxExclusive"
	xsdFacetMaxInclusive   = "maxInclusive"
	xsdFacetMaxLength      = "maxLength"
	xsdFacetMinExclusive   = "minExclusive"
	xsdFacetMinInclusive   = "minInclusive"
	xsdFacetMinLength      = "minLength"
	xsdFacetPattern        = "pattern"
	xsdFacetTotalDigits    = "totalDigits"
	xsdFacetWhiteSpace     = "whiteSpace"

	xsdValueQualified     = "qualified"
	xsdValueUnqualified   = "unqualified"
	xsdValueToken         = "token"
	xsdWhitespaceCollapse = "collapse"
	xsdWhitespacePreserve = "preserve"
	xsdWhitespaceReplace  = "replace"
)
