package schemair

import ast "github.com/jacoelho/xsd/internal/schemaast"

func BuiltinTypeNames() []ast.TypeName {
	return []ast.TypeName{
		ast.TypeNameAnyType,
		ast.TypeNameAnySimpleType,
		ast.TypeNameString,
		ast.TypeNameBoolean,
		ast.TypeNameDecimal,
		ast.TypeNameFloat,
		ast.TypeNameDouble,
		ast.TypeNameDuration,
		ast.TypeNameDateTime,
		ast.TypeNameTime,
		ast.TypeNameDate,
		ast.TypeNameGYearMonth,
		ast.TypeNameGYear,
		ast.TypeNameGMonthDay,
		ast.TypeNameGDay,
		ast.TypeNameGMonth,
		ast.TypeNameHexBinary,
		ast.TypeNameBase64Binary,
		ast.TypeNameAnyURI,
		ast.TypeNameQName,
		ast.TypeNameNOTATION,
		ast.TypeNameNormalizedString,
		ast.TypeNameToken,
		ast.TypeNameLanguage,
		ast.TypeNameName,
		ast.TypeNameNCName,
		ast.TypeNameID,
		ast.TypeNameIDREF,
		ast.TypeNameIDREFS,
		ast.TypeNameENTITY,
		ast.TypeNameENTITIES,
		ast.TypeNameNMTOKEN,
		ast.TypeNameNMTOKENS,
		ast.TypeNameInteger,
		ast.TypeNameLong,
		ast.TypeNameInt,
		ast.TypeNameShort,
		ast.TypeNameByte,
		ast.TypeNameNonNegativeInteger,
		ast.TypeNamePositiveInteger,
		ast.TypeNameUnsignedLong,
		ast.TypeNameUnsignedInt,
		ast.TypeNameUnsignedShort,
		ast.TypeNameUnsignedByte,
		ast.TypeNameNonPositiveInteger,
		ast.TypeNameNegativeInteger,
	}
}
